spring.profiles.default: local
spring.config:
  import:
    - classpath:/application-core.yml

server:
  port: 9999
  shutdown: graceful
  servlet:
    encoding:
      charset: UTF-8
      force: true
    context-path: /api

spring:
  application:
    name: untitled-api
  mvc:
    format:
      date: iso
      date-time: iso
      time: iso
